language: elixir

sudo: false

jobs:
  include:
    - stage: check formatted
      script: mix format --check-formatted
      otp_release: 20.3
      elixir: 1.7
    - stage: test
      script: mix test
      otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.7
